### ISSUE TITLE
identifier 'count' undefined in iOS find-classes.js

### ISSUE THREAD

**Issue by ITmustang** [interference-security/frida-scripts#1]
frida -U -l find-classes.js DVIA-v2
     ____
    / _  |   Frida 12.8.7 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
Attaching...                                                            
[*] Started: Find Classes
ReferenceError: identifier 'count' undefined
    at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:81144)
    at show_classes_of_app (/find-classes.js:4)
    at /find-classes.js:16

**change to: var count = 0**

**Comment by interference-security** [comment]
The issue has been fixed now. I have to fix this in all scripts. Should be done soon. Thanks for the contribution.
