### ISSUE TITLE
ReferenceError: identifier 'newretval' undefined ios show-modify-method-return-value.js

### ISSUE THREAD

**Issue by ITmustang** [interference-security/frida-scripts#2]
ReferenceError: identifier 'newretval' undefined
    at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:81144)
    at /show-modify-method-return-value.js:13 

newretval = ptr("0x0");

need to change to
**var newretval = ptr("0x0");**

**Comment by interference-security** [comment]
The issue has been fixed now. I have to fix this in all scripts. Should be done soon. Thanks for the contribution.
