### ISSUE TITLE
undefined variable in dump-ui.js

### ISSUE THREAD

**Issue by ITmustang** [interference-security/frida-scripts#3]
frida -U -l dump-ui.js (app)
     ____
    / _  |   Frida 12.8.10 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://www.frida.re/docs/home/
Attaching...    

[*] Started: Dumping UI
ReferenceError: identifier 'current_window' undefined
    at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:81144)
    at /dump-ui.js:5

current_window = ObjC.classes.UIWindow.keyWindow()
change to
var current_window = ObjC.classes.UIWindow.keyWindow()

**Comment by interference-security** [comment]
This issue has been fixed now. Thanks for the contribution.
